<?php

namespace AppBundle\Repository;
use DateTime;

/**
 * AdvertisingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNotExpiredAd($place){
        return $this->createQueryBuilder('a')
            ->where('a.expireAt >= :today')
            ->setParameter('today', new DateTime())
            ->andWhere("a.place = $place")
            ->getQuery()
            ->getResult();
    }
}
