<?php

namespace AppBundle\Repository;

/**
 * BanerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanerRepository extends \Doctrine\ORM\EntityRepository
{
}
