<?php

namespace AppBundle\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastPublishedBlogs($limit = 2){
        return $this->createQueryBuilder('b')
            ->where('b.published = true')
            ->setMaxResults($limit)
            ->orderBy('b.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
