<?php

namespace AppBundle\Repository;

/**
 * IncorrectAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncorrectAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
