<?php

namespace AppBundle\Repository;

/**
 * LawbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LawbookRepository extends \Doctrine\ORM\EntityRepository
{
}
