<?php

namespace AppBundle\Repository;

/**
 * LawbookCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LawbookCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
