<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * LawbookCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LawbookCategoryRepository extends EntityRepository
{
    public function getPublicCategoriesData(){
        return $this->createQueryBuilder('c')
            ->innerJoin("c.lawbooks", "l")
            ->where("l.freeDownload = true")
            ->andWhere("l.published = true")
            ->getQuery()
            ->getResult();
    }
}
