<?php

namespace AppBundle\Repository;

/**
 * NewsletterRecipientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRecipientRepository extends \Doctrine\ORM\EntityRepository
{
}
