<?php

namespace AppBundle\Repository;

/**
 * NewsLetterEmailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsLetterEmailsRepository extends \Doctrine\ORM\EntityRepository
{
}
