<?php

namespace AppBundle\Repository;

/**
 * PaymentTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
