<?php

namespace AppBundle\Repository;

/**
 * PracticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PracticeRepository extends \Doctrine\ORM\EntityRepository
{
}
