<?php

namespace AppBundle\Repository;

/**
 * questionCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class questionCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
