<?php

namespace AppBundle\Repository;

/**
 * verbalQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class verbalQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
