<?php

namespace AppBundle\Repository;

/**
 * WrittenQuestionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WrittenQuestionCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
