<?php

namespace AppBundle\Repository;

/**
 * writtenQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class writtenQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
