<?php

namespace AppBundle\Repository;

/**
 * WrittenQuestionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WrittenQuestionCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNotEmptyCategories(){
        return $this->createQueryBuilder('c')
            ->innerJoin("c.writtenQuestions", "q")
            ->select("c")
            ->where("c.id = q.category")
            ->getQuery()
            ->getResult();
    }
}
