<?php

namespace AppBundle\Repository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * writtenQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class writtenQuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllIds()
    {
        return $this->createQueryBuilder('w')
            ->select('w.id')
            ->getQuery()
            ->getResult();
    }

    public function getAllIdsForCategory($category)
    {
        return $this->createQueryBuilder('w')
            ->select('w.id')
            ->where("w.category = $category" )
            ->getQuery()
            ->getResult();
    }

    public function getIDsRange()
    {
        try {
            return $this->createQueryBuilder('w')
                ->select('MAX(w.id) as maxId', 'MIN(w.id) as minId')
                ->getQuery()
                ->getSingleResult();
        } catch (NoResultException $e) {

        } catch (NonUniqueResultException $e) {

        }
    }
}
