# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_VIP: [ROLE_USER]
        ROLE_ADMIN: [ROLE_VIP]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        FOS\UserBundle\Model\UserInterface: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$hZ2hpfT0nrHnIcXIFhK/vO7rl9Ca6753zx8rNspsEgautKSFuoJxu
                        roles: 'ROLE_ADMIN'
                    kamil:
                        password: $2y$13$hZ2hpfT0nrHnIcXIFhK/vO7rl9Ca6753zx8rNspsEgautKSFuoJxu
                        roles: 'ROLE_ADMIN'

        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

#            pattern: ^/
#            provider: in_memory
#            form_login:
#                login_path: login
#                check_path: login
#            logout: true
#            anonymous: ~
#            logout_on_user_change: true

        fosUser:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }