<?php
/**
 * Created by PhpStorm.
 * User: toma4
 * Date: 30.03.2018
 * Time: 23:56
 */

namespace AppBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;

class NewsletterRecipientType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
            ->add("email", EmailType::class, array('attr' => array('placeholder' => 'Podaj twój E-mail', 'class' => 'form-control')));
    }
}