<?php
/**
 * Created by PhpStorm.
 * User: toma4
 * Date: 16.03.2018
 * Time: 22:20
 */

namespace AppBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class testType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder
//            ->add('field', 'Ivory\CKEditorBundle\Form\Type\CKEditorType', array('config' => array('uiColor' => '#ffffff', /* */),))
            ->add('field', 'Ivory\CKEditorBundle\Form\Type\CKEditorType')
            ->add("submit", 'Symfony\Component\Form\Extension\Core\Type\SubmitType', ["label" => "zapisz"]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        //$resolver->setDefaults(["data_class" => Movie::class]); // zastepuje w kontrolerze $movie = $form->getData(); - wstawianie danych do klasy film
    }
}